### ISSUE TITLE
Add in flame magic concept

### ISSUE THREAD

**Issue by anleac** [anleac/defend_your_flame#64]
I'd like to add in the concept of "flame magic" which generates slowly each round (based on the strength of your flame), and can be used for defensive spells.

**Comment by mboisvertdupras** [comment]
On it chief 💪 😎

**Comment by anleac** [comment]
Closed wrong issue, thanks for taking this on!

**Comment by anleac** [comment]
Added in https://github.com/anleac/defend_your_flame/pull/90
